// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKG06SLZVnnjGrYr65AuZuZqtVs14kHzE',
    appId: '1:694938247798:web:6d0278926f4ecfbbcdf557',
    messagingSenderId: '694938247798',
    projectId: 'chat-app-d0274',
    authDomain: 'chat-app-d0274.firebaseapp.com',
    storageBucket: 'chat-app-d0274.firebasestorage.app',
    measurementId: 'G-6NGDLM2L12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdYhPJgmeTlzfYZUYoiVQZka72lKyCbKw',
    appId: '1:694938247798:android:a1bae073594139a1cdf557',
    messagingSenderId: '694938247798',
    projectId: 'chat-app-d0274',
    storageBucket: 'chat-app-d0274.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe1xC67GF4970UCOhTyzGNR4UH0rWtBCA',
    appId: '1:694938247798:ios:97d89cd7117d50c5cdf557',
    messagingSenderId: '694938247798',
    projectId: 'chat-app-d0274',
    storageBucket: 'chat-app-d0274.firebasestorage.app',
    iosBundleId: 'com.example.belal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe1xC67GF4970UCOhTyzGNR4UH0rWtBCA',
    appId: '1:694938247798:ios:97d89cd7117d50c5cdf557',
    messagingSenderId: '694938247798',
    projectId: 'chat-app-d0274',
    storageBucket: 'chat-app-d0274.firebasestorage.app',
    iosBundleId: 'com.example.belal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKG06SLZVnnjGrYr65AuZuZqtVs14kHzE',
    appId: '1:694938247798:web:8542f4723828bfc9cdf557',
    messagingSenderId: '694938247798',
    projectId: 'chat-app-d0274',
    authDomain: 'chat-app-d0274.firebaseapp.com',
    storageBucket: 'chat-app-d0274.firebasestorage.app',
    measurementId: 'G-DGWZNB6802',
  );
}
